---
title: "Gapminder Exercise Template"
author: "Becky Tang"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 7)
```


## Load packages

```{r message=FALSE}
library(tidyverse)
```

```{r}

```


## Load data

```{r message = F}
gap <- read_csv("https://bit.ly/gap_data_upd")
```

## Exercises

### Exercise 1

How many observations are in this dataset?

```{r nrow}
nrows <- nrow(gap)
```

There are `r nrows` observations in this dataset.

### Exercise 2

Visualize the relationship between GDP and life expectancy for 
countries in Europe in 1952 using a scatter plot.

```{r eu_52, echo = F}
eu_52 <- gap %>% filter(continent == "Europe", year == 1952) 
ggplot(data = eu_52, aes(x = gdpPercap, y = lifeExp)) + geom_point()
```

### Exercise 3

Add year 1967 in another color.

```{r eu_52_67, echo = F}
#Create a subset of gap for Europe in 1952 and 1967 and call it eu_5267
eu_5267 <- gap %>% filter(continent == "Europe", year %in% c(1952, 1967))

ggplot(data = eu_5267, aes(x = gdpPercap, y = lifeExp, color = factor(year))) + geom_point()
```

